name: Wake Up SupremeNode
on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes to keep it from sleeping
  workflow_dispatch:      # Allows you to test it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face Space
        run: |
          curl -I -s -L https://supreme100-supremenodess.hf.space | grep "HTTP/"
